### ISSUE TITLE
Consider restoring Web Store link

### ISSUE THREAD

**Issue by vslavik** [DevMate/DevMateKit#15]
Apparently, at some point after v1.5, DevMakeKit removed the Web Store link that allowed "paranoid" customers to purchase in their browser rather than in-app. For reference, this is how it used to look:
<img width="692" alt="screen shot 2016-03-18 at 09 01 15" src="https://cloud.githubusercontent.com/assets/145881/13881551/9bf1f3a6-ed21-11e5-930d-80ca8dab7dad.png">
That the link is now gone was a bit of a  surprise, because release notes don't mention it. I only found an indirect deprecation note [here in the headers](https://github.com/DevMate/DevMateKit/blob/02bef345d8655dbed935e7d593dc80f16d2d8bb5/DevMateKit/DevMateKit.framework/Versions/A/Headers/DMWelcomeStepController.h#L16) later, otherwise I would assume it was a bug, not intentional.

While I understand how it doesn't fit very well with the [reordered buttons](http://blog.devmate.com/post/141140551341/a-simple-ab-split-test-to-boost-your-app), it's still something that is useful: according to my records, some 10-20% of my users prefer to purchase in their browser. It would be nice to have it back e.g. in the titlebar next to the padlock icon.

This is another practical example of the usefulness of the framework being Open Source (#14). I currently work around it by adding a link to the embedded store's HTML and hijacking the click with a WebView policy delegate, but it would be less work, more robust code and better UI if I modified the framework directly...

**Comment by dimaty** [comment]
Our idea was to provide link to web store on the embedded store step, inside the HTML code, as you have done. Other way is to customize this view by adding another button, that will do the same action.

**Comment by vslavik** [comment]
Neither is particularly easy to do, though...
