### ISSUE TITLE
Make "Send & Relaunch" default button for crash alert

### ISSUE THREAD

**Issue by ivira** [DevMate/DevMateKit#16]
Crash alert has two action buttons: "Send" and "Send and Relaunch". "Send" is default one.
I think that "Send and Relaunch" is better default behavior and is more aligned with Apple native behavior http://cdn2.macworld.co.uk/cmsdata/features/3426075/App_Crash_Report.jpg

**Comment by dimaty** [comment]
Done in v1.8.
