### ISSUE TITLE
Enabling automatic updates in Swift

### ISSUE THREAD

**Issue by rudedogg** [DevMate/DevMateKit#19]
In my AppDelegate applicationDidFinishLaunching I have:
`DM_SUUpdater.sharedUpdater().automaticallyChecksForUpdates = true`

Do I need to do anything else to have the app check for updates? I setup the delegate method and can see it's getting called when I use the menu item and run:
`DevMateKit.checkForUpdates(nil, includeBetaCheck: false, inTestMode: false)`

But due to the timer, I can't tell if it's called automatically on app start (I had manually checked for updates previously).

**Comment by dimaty** [comment]
Hi.
Yes, you are doing everything right. Setting up `automaticallyChecksForUpdates` property causes to restart checking timer and it will fire after `SUMinimumUpdateCheckInterval` from the last check (you can check this in Sparkle sources). And `DevMateKit.checkForUpdates...` cuases to run updater immediately (but with UI).

**Comment by rudedogg** [comment]
@dimaty Thank you for the explanation and confirmation!
