### ISSUE TITLE
Updater: App Transport Security

### ISSUE THREAD

**Issue by macmade** [DevMate/DevMateKit#2]
Updater in version **1.2** fails on OS X 10.11 betas due to the new **App Transport Security** feature, which prevents non-secure connections.

This relates to `NSURLConnection`, `CFURL`, and `NSURLSession`.

The issue is probably because the updater issue its requests using **HTTP** instead of **HTTPS**, but the request may fail even with HTTPS if the DevMate servers are not compatible with App Transport Security.

Requirements are:

 * The server must support at least Transport Layer Security (TLS) protocol version 1.2.
 * Connection ciphers are limited to those that provide forward secrecy.
 * Certificates must be signed using a SHA256 or better signature hash algorithm, with either a 2048 bit or greater RSA key or a 256 bit or greater Elliptic-Curve (ECC) key.
 * Invalid certificates result in a hard failure and no connection.

I'm aware I can list exceptions in the app's `Info.plist` file, but I don't consider this as a valid long-term solution.

Final version of OS X 10.11 will be available **very soon**. Can we hope for an updated version before the release date?

Note: more info on App Transport Security:
https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/index.html#//apple_ref/doc/uid/TP40016240-CH1-SW3

**Comment by macmade** [comment]
Note: issue is still present in pre-release version 1.3: ca9686875b94f00b20bac92c94182204e631312f

**Comment by dimaty** [comment]
Yes, we're working on it with our server side.

**Comment by dimaty** [comment]
@macmade Fixed server side to support ATS.

**Comment by macmade** [comment]
@dimaty Thank you, everything is fine now.

Note that I had to remove `SUFeedURL` from the preferences. Previous versions of DevMate were using an `http` scheme, and version 1.3 takes the value from the preferences if present.
