### ISSUE TITLE
Can't build Example projects with Xcode 8

### ISSUE THREAD

**Issue by SoneeJohn** [DevMate/DevMateKit#20]
I was unable to build the example project due to this error:

`ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by dimaty** [comment]
Hi.
Thank you for your report. We'll check Examples project and DevMateKit itself with new Xcode 8 in the next few days.

**Comment by GuriK** [comment]
@SoneeJohn 
you need to compile openssl and link libcrypto.a to project. This fixed problem for me.
Here is gist https://gist.github.com/tmiz/1441111

**Comment by SoneeJohn** [comment]
@GuriK the issue was fixed with Kevlar version 4.2 see the release notes here: https://docs.devmate.com/v1.0/docs/kevlar-release-notes

**Comment by boyvanamstel** [comment]
I still ran into this, but after reading the release notes it says that you can build without linking to libcrypto.

@SoneeJohn The tutorial also still mentions having to link libcrypto: https://docs.devmate.com/docs/activations-and-trial.

**Comment by dimaty** [comment]
Sorry guys. Doc is fixed ;)

**Comment by boyvanamstel** [comment]
👌👌👌

**Comment by m1entus** [comment]
Can you give us a link to Kevalr 4.2 or update repo ?

**Comment by SoneeJohn** [comment]
@m1entus you can find it by going to the DevMate Dashboard  and clicking on the respective application. Then click on settings in the sidebar, then click `Activations and Trial`.

![screen shot 2016-09-14 at 4 24 22 pm](https://cloud.githubusercontent.com/assets/4827301/18528670/03c28fd2-7a98-11e6-974c-b1fb22a4b6d3.png)

**Comment by m1entus** [comment]
I have still issue with libcrypto then `ld: library not found for -lcrypto`

**Comment by SoneeJohn** [comment]
@m1entus you might still have references to `-lcrypto` in the other linker flags setting. I had this problem when upgrading if, that doesn't work try cleaning the build folder.

<img width="1164" alt="screen shot 2016-09-14 at 4 34 16 pm" src="https://cloud.githubusercontent.com/assets/4827301/18528977/3783ca10-7a99-11e6-8257-1920227f0089.png">

**Comment by dimaty** [comment]
@SoneeJohn Thank you for your help ;)

@m1entus Yes, you should download Kevlar from the DevMate Dashboard as it's unique for each application, and activation won't work with Kevlar for the other app. And now you don't need to link your target with _crypto_ library, just remove it from "Build Settings".
