### ISSUE TITLE
Issue Reporting - Additional Info not used

### ISSUE THREAD

**Issue by macmade** [DevMate/DevMateKit#23]
I'm trying to send additional info when a crash occurs using the `additionalIssueInfoForController:` delegate method of the `DMIssuesControllerDelegate` protocol.

Unfortunately, it looks like the feature is not implemented.  
The additional info is not sent to DevMate.

I've looked at the DevMateKit binary, and the `additionalIssueInfoForController:` selector is referenced in `-[DMIssuesController additionalReportInfo:]:`.

But `-[DMIssuesController additionalReportInfo:]:` is not referenced anywhere.  
That method is simply not called. So no surprise nothing is sent to the DevMate servers.

Would be great if you could fix this quickly...

**Comment by dimaty** [comment]
> Unfortunately, it looks like the feature is not implemented.
Yes, that's true. But this feature is not implemented on server side yet. You can check it by putting breakpoint at `additionalIssueInfoForController:` delegate method implementation. Make sure your object that implements this method is passed as delegate on IssueReporter setup.

**Comment by macmade** [comment]
Any idea when this will be implemented?

**Comment by storyer** [comment]
Hi, 

Thanks a lot, we've added this feature to the backlog so our developers already have this feature in their todo list. 

At the moment I'm not able to give you more exact timeline for this feature as our developers currently overloaded. 

Regards,
DevMate Team

**Comment by macmade** [comment]
Any new on this issue?

**Comment by dimaty** [comment]
This API is removed from framework in v1.8 until this feature won't be presented in DevMate dashboard.
