### ISSUE TITLE
11 typos in DMKevlarApplicatiom.h

### ISSUE THREAD

**Issue by ianbytchek** [DevMate/DevMateKit#24]
![image](https://cloud.githubusercontent.com/assets/1086845/19693861/33c43228-9aee-11e6-8ba2-091d44f33682.png)

**Comment by SoneeJohn** [comment]
@ianbytchek just out of curiosity, but what is the name of the app that you're using?

**Comment by ianbytchek** [comment]
[AppCode](https://www.jetbrains.com/objc) – it's amazing like most of [JetBrains](https://www.jetbrains.com) products :heart_eyes_cat:

**Comment by dimaty** [comment]
Fixed in Kevlar v4.3.
