### ISSUE TITLE
Please annotate framework headers for nullability

### ISSUE THREAD

**Issue by tonyarnold** [DevMate/DevMateKit#29]
Using DevMateKit can be a little cumbersome from Swift right now, as none of the headers in the released version of the framework have been audited for nullability. 

It ends up unnecessarily requiring nil checks in Swift code, i.e.:

```swift
if let controller = DMActivationController.shared() {
    // …
}

// Or worse:

let controller = DMActivationController.shared()!
```

If  in this instance (and others I'm sure I am missing) the original headers should really be marked as `nonnull`, i.e.:

```objective-c
//! Main controller class for activation.
@interface DMActivationController : NSWindowController

/*! @brief Method for getting shared controller instance.
    @return Shared controller instance.
*/
+ (nonnull instancetype)sharedController;

/*! @brief Initializes new controller with default window.
    @discussion To use your own XIB for controller use \p-initWithWindowNibName: method instead.
    @return New autoreleased controller with default window.
*/
+ (nonnull instancetype)defaultController;

@end
```

**Comment by dimaty** [comment]
Hi all.
Take a look at DevMateKit v1.9.

**Comment by tonyarnold** [comment]
Looks good, thanks! Any chance you could flesh out the Objective-C lightweight generics support on things like NSArrays and NSDictionaries?

**Comment by dimaty** [comment]
Maybe with next releases. You can add another issue for this. This one I'm closing.
