### ISSUE TITLE
Using Kevlar in a Objective-C console app (without an Info.plist)

### ISSUE THREAD

**Issue by codebar33** [DevMate/DevMateKit#33]
Hey DevMate team,

This is more a question than an issue. We are currently developing a CLI version of iMazing and would like to use DevMate Kevlar lib to manage the activation. The app is a Console Objective-C app and obviously there is not Info.plist packaged with it.

So we tried to do this trick:

`@interface NSBundle( iMazingCLI )

-( NSDictionary * )iMazingInfoDictionary;

@end

@implementation NSBundle( iMazingCLI )

-( NSDictionary * )iMazingInfoDictionary
{
    NSMutableDictionary * info = self.iMazingInfoDictionary.mutableCopy;
    
    info[ @"CFBundleIdentifier" ] = @"com.DigiDNA.iMazingMac.CLI";
    info[ @"CFBundleShortVersionString" ] = @"1.0.0";
    
    return info;
}

@end

static void init( void ) __attribute__( ( constructor ) );
static void init( void )
{
    Method m1;
    Method m2;
    
    m1 = class_getInstanceMethod( [ NSBundle class ], @selector( infoDictionary ) );
    m2 = class_getInstanceMethod( [ NSBundle class ], @selector( iMazingInfoDictionary ) );
    
    method_exchangeImplementations( m1, m2 );
}`

But it doesn't work, when we call `activationDone = NO;
    [
        NSApp
        activateWithInfo:activationInfo
        completionHandler: ^( BOOL success, NSError * error )
        {
            ( void )success;
            ( void )error;
            
            activationDone = YES;
        }
    ];
`
the completionHandler is never called.

Any idea?

**Comment by dimaty** [comment]
Have you tried to change build setting CREATE_INFOPLIST_SECTION_IN_BINARY to YES and for your CLI target instead of swizzling methods?

**Comment by codebar33** [comment]
That's a very good idea, I didn't know this solution, I will try and let you know :)

**Comment by codebar33** [comment]
OK I did use CREATE_INFOPLIST_SECTION_IN_BINARY and it works fine, when calling `NSLog( @"%@", [ NSBundle mainBundle ].infoDictionary );`  I get ```{
    BuildMachineOSBuild = 17E199;
    CFBundleIdentifier = "com.DigiDNA.iMazingMac.CLI";
    CFBundleShortVersionString = "1.0.0";
    CFBundleSupportedPlatforms =     (
        MacOSX
    );
    CFBundleVersion = 1;
    DTCompiler = "com.apple.compilers.llvm.clang.1_0";
    DTPlatformBuild = 9E145;
    DTPlatformVersion = GM;
    DTSDKBuild = 17E189;
    DTSDKName = "macosx10.13";
    DTXcode = 0930;
    DTXcodeBuild = 9E145;
}``` in the console...  

but I still have the same behaviour, the completionHandler is not called (I have loop while waiting for variable activationDone to be true after the call to activateWithInfo)

**Comment by dimaty** [comment]
Ok, thanks for reporing this issue. We need more time to investigate the reason.

**Comment by codebar33** [comment]
OK great, we tried to disassemble Kevlar to understand how it works but it's pretty obfuscated ;)  I also tried to add a breakpoint on -[NSApplication activateWithInfo:completionHandler:]   but it never fires

**Comment by dimaty** [comment]
Have you checked if `NSApp` variable is already initiated (not `nil`) at the time you call `-activateWithInfo...` method?

**Comment by codebar33** [comment]
Oh my god, we forgot to check that ;(   Thanks a lot, it works fine with `[ NSApplication sharedApplication ]`... Not sure why NSApp is not initialized at this stage...  Thanks a lot for your help and the nice solution `CREATE_INFOPLIST_SECTION_IN_BINARY `
