### ISSUE TITLE
activateWithInfo, completionHandler never called

### ISSUE THREAD

**Issue by codebar33** [DevMate/DevMateKit#34]
Hi,

I reopen this one.  I thought it was working last week but it's not..  So activation now works fine when using `[ NSApplication sharedApplication ]` instead of `NSApp` in an Objective-C console app.  But the completionHandler is never called so it makes the integration difficult to achieve, even if I put a sleep of 20 seconds instead of the while loop, before calling `DMKIsApplicationActivated`, `DMKIsApplicationActivated` return false with DMKevlarError `DMKevlarActivationInProcess`. But then after when I relaunch the app, the app is activated so activation worked fine.  

Here is the code:

    activationDone = NO;
    [
        [ NSApplication sharedApplication ]
        activateWithInfo: activationInfo
        completionHandler:
        ^( BOOL success, NSError * error )
        {
            ( void )success;
            ( void )error;
            
            activationDone = YES;
        }
    ];

    while( !activationDone )
    {
        sleep( 1 );
    }

    DMKevlarError error;

    if( DMKIsApplicationActivated( &error ) )
    {
        return true;
    }

    return false;

**Comment by codebar33** [comment]
I also tried to call activateWithInfo from a dispatch_async, it didn't work either.

**Comment by dimaty** [comment]
We're preparing an update of Kevlar lib this week that should fix your problem. It would be great if you give us a bundle id of your CLI app, and we send you a new copy of lib to test this issue. Can you do this as a new comment here or via support message?

**Comment by codebar33** [comment]
Hi Dimaty, thanks a lot, our CLI bundle ID is: `com.DigiDNA.iMazingMac.CLI`

**Comment by codebar33** [comment]
Hi Dimaty, many thanks for the fix, I just tested wot the new Kevlar build and it works!
