### ISSUE TITLE
[Question] A way to determine number of days left for trial?

### ISSUE THREAD

**Issue by guidedways** [DevMate/DevMateKit#37]
I can't seem to find the obvious. How can one determine the number of days left for a user's trial at runtime?

**Comment by SoneeJohn** [comment]
@guidedways  see `DMTrialGetTrialValueLeft` (https://github.com/DevMate/DevMateKit/blob/9544a56ee5fa8910de0fdb57a1a2bd7e8214cf62/DevMateKit/DevMateKit.framework/Versions/A/Headers/DMTrial.h#L160)

**Comment by guidedways** [comment]
Excellent, missed it somehow! Thanks.

**Comment by dimaty** [comment]
Thank you @SoneeJohn!
