### ISSUE TITLE
Support for macOS 10.14 Dark Mode

### ISSUE THREAD

**Issue by macmade** [DevMate/DevMateKit#38]
Current version (1.8.2) doesn't look great with the new dark mode in macOS 10.14:

<img width="655" alt="devmate" src="https://user-images.githubusercontent.com/146476/43201470-e3ea6e76-9018-11e8-8fe5-96dd2230b2a5.png">

Do you have an ETA for a fixed version?

**Comment by GregularExpressions** [comment]
Hey @macmade 

We're looking into this at the moment, no hard timelines but definitely before the 10.14 launch in (likely) October - we're aiming for at least 4 weeks before.

Thanks,
Greg.

**Comment by macmade** [comment]
Thanks for the info.

We can force the aqua appearance on DevMate windows for now, so no worries.

**Comment by tonyarnold** [comment]
@macmade you should probably re-open this until we actually get this in a released binary. It'll stop others from posting the same issue as well.

**Comment by macmade** [comment]
Any news on this?

**Comment by dimaty** [comment]
Hi @macmade. Yes, we are working on it. Actually it's in testing phase. Planing to release it next week.

**Comment by dimaty** [comment]
Hi all.
Check DevMateKit v1.9. If you'll some problems with Dark Mode on Mojave, just let me know.

**Comment by macmade** [comment]
Everything looks good now...
