### ISSUE TITLE
Pod Issues

### ISSUE THREAD

**Issue by rudedogg** [DevMate/DevMateKit#39]
I was trying to configure two build schemes for a Mac App Store and non-Mac App Store version. I ran into issues getting this to work, and a contributor for CocoaPods pointed out some issues with the podspec and `module.modulemap` file at https://github.com/CocoaPods/CocoaPods/issues/7990#issuecomment-413747505.

I'd really like to get this config working, it'll make doing updates/releases a lot easier for me. Could we get these fixed on the `DevMateKit` and `DevMateKit_MAS` pods so a config like mine will work?

Thanks,
Austin

**Comment by dimaty** [comment]
DevMateKit does not support module feature because it has macro inside master header
```
// If you are using your own copy of Sparkle.framework just define
// USED_CUSTOM_SPARKLE_FRAMEWORK macro.
#ifndef USED_CUSTOM_SPARKLE_FRAMEWORK
#import "DevMateSparkle.h"
#endif
```

Try to resolve your issue by adding bridging header to your Swift target and add `#import <DevMateKit/DevMateKit.h>` there.
 If you're using your own copy of Sparkle for updates add to that header next:
```
#define USED_CUSTOM_SPARKLE_FRAMEWORK
#import <DevMateKit/DevMateKit.h>
```

**Comment by dimaty** [comment]
Hi, @rudedogg. Have you tried solution above?
