### ISSUE TITLE
Hardened Runtime support

### ISSUE THREAD

**Issue by nikolaeu** [DevMate/DevMateKit#40]
In Xcode 10 when hardened runtime enabled for the host app, getting error prior to sending app to notary service:

```
Hardened Runtime is not enabled.

"Autoupdate.app", "Problem Reporter Sandboxed.app", "Problem Reporter.app", "com.devmate.UpdateInstaller.xpc", and "fileop" must be rebuilt with support for the Hardened Runtime. Enable the Hardened Runtime capability in the project editor, then test your app, rebuild your archive, and upload again.
```

**Comment by SoneeJohn** [comment]
@dimaty Any update on this? I disabled _Library Validation_ but am still getting the same issue as @nikolaeu.

**Comment by macmade** [comment]
We got rid of this issue by re-signing DevMate components in our app.

Not sure there’s another solution, as bundled frameworks need to be signed by the same developer team.

So use a custom script build phase, and invoke the codesign utility with the -force option, signing all frameworks and apps in DevMateKit with your own Developer ID...

**Comment by SoneeJohn** [comment]
@macmade Thanks! I thought that was what disabling Library Validation was supposed to enable.

**Comment by macmade** [comment]
@SoneeJohn Something like this should get you started:

```
codesign --sign "<YOUR_DEVELOPER_ID>" --force --options runtime "${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"/"DevMateKit.framework/Frameworks/DevMateIssuesReporter.framework/Versions/A/Frameworks/CrashReporter.framework"
codesign --sign "<YOUR_DEVELOPER_ID>" --force --options runtime "${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"/"DevMateKit.framework/Frameworks/DevMateIssuesReporter.framework"
codesign --sign "<YOUR_DEVELOPER_ID>" --force --options runtime "${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"/"DevMateKit.framework/XPCServices/com.devmate.UpdateInstaller.xpc"
codesign --sign "<YOUR_DEVELOPER_ID>" --force --options runtime "${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"/"DevMateKit.framework/Resources/Autoupdate.app"
codesign --sign "<YOUR_DEVELOPER_ID>" --force --options runtime "${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"/"DevMateKit.framework/Resources/Autoupdate.app"
codesign --sign "<YOUR_DEVELOPER_ID>" --force --options runtime "${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"/"DevMateKit.framework/Resources/Autoupdate.app/Contents/MacOS/fileop"
codesign --sign "<YOUR_DEVELOPER_ID>" --force --options runtime "${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"/"DevMateKit.framework/Resources/Problem Reporter Sandboxed.app"
codesign --sign "<YOUR_DEVELOPER_ID>" --force --options runtime "${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"/"DevMateKit.framework/Resources/Problem Reporter.app"
```

**Comment by dimaty** [comment]
Enabled Hardened Runtime in version 1.9.2.

**Comment by nikolaeu** [comment]
Yay! Thank you @dimaty 👏🏻

**Comment by simonmaddox** [comment]
![cleanshot 2018-11-09 at 16 36 07](https://user-images.githubusercontent.com/34273/48275554-aeb47480-e43d-11e8-8b47-647c899d974d.png)

Hi @dimaty,

Did you miss one of your sub-applications when enabling Hardened Runtime? Or am I doing something wrong?

**Comment by simonmaddox** [comment]
@adriangranados interesting, thank you. I must be doing something wrong then. I’ll take a look, and report back when I know more.

**Comment by dimaty** [comment]
Hi, @simonmaddox.
Are you using DevMateKit for Mac AppStore (MAS)? My guess is that you run `update_reporter_id.sh`. This script changes `Info.plist` file (changes CFBundleIdentifier value) of 'Problem Reporter Sandboxed.app' and then re-sign it with your certificate. Update this script:
instead
```
if [ -f "${REPORTER_ENTITLEMENTS}" ]; then
    codesign -fv -s "${SIGN_IDENT}" --entitlements "${REPORTER_ENTITLEMENTS}" "${REPORTER_APP}"
else
    codesign -fv -s "${SIGN_IDENT}" "${REPORTER_APP}"
fi
```

use
```
if [ -f "${REPORTER_ENTITLEMENTS}" ]; then
    codesign -fv -s "${SIGN_IDENT}" --entitlements "${REPORTER_ENTITLEMENTS}" "${REPORTER_APP}" --options runtime
else
    codesign -fv -s "${SIGN_IDENT}" "${REPORTER_APP}" --options runtime
fi
```
and try to validate again.

**Comment by rolandleth** [comment]
Hey, @dimaty!

I'm having issues with this, as well. I'm new to Mac development, so it might just be that it's my lack of knowledge.

I get no errors, but it asks me to select Developer ID certificates and I have to fill in these:
<img width="569" alt="screenshot 2019-02-08 at 12 31 25" src="https://user-images.githubusercontent.com/1858700/52473021-75ef7d00-2b9d-11e9-9084-fb11ec290499.png">

For my app and helper I have profiles, of course, but what should I do for these? Am I doing anything wrong? I installed DevMateKit via CocoaPods.

Thank you!

**Comment by dimaty** [comment]
Do you have an option in this Xcode's dialog just leave as is and press 'Next' button?

**Comment by rolandleth** [comment]
o.m.g 🤦🏻‍♂️ I didn't realise the Next button is enabled.

I'm sorry for wasting your time, Dmytro, and thanks!

Have a wonderful day and weekend!
