### ISSUE TITLE
error when installing DevMate via pods

### ISSUE THREAD

**Issue by paganel** [DevMate/DevMateKit#41]
log
Installing DevMateKit (1.8.2)

[!] Error installing DevMateKit
[!] /usr/bin/curl -f -L -o /var/folders/hp/q99rwkks5d13q27881m9fc1h0000gn/T/d20180911-1744-18ambxw/file.zip https://github.com/DevMate/DevMateKit/releases/download/v1.8.2/DevMateKit_for_pod.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server

**Comment by dimaty** [comment]
Hi @paganel.
I'm not sure this is an issue with framework itself. We host all released versions of DevMateKit on GitHub. Does it reproduce each time when you try to download resource?

**Comment by paganel** [comment]
Прошу прощения, оказалось что Lulu/BlockBlock блокировал подключение
