### ISSUE TITLE
DevMateKit_MAS 1.9 App sandbox not enabled error

### ISSUE THREAD

**Issue by teologov** [DevMate/DevMateKit#42]
Hi, I've updated my app to the latest `DevMateKit_MAS 1.9` in order to resolve dark mode issue on macOS Mojave.

Now I can't upload the build to AppStore. It fails with the next error:

```
App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list: [( "com.my.App.pkg/Payload/MyApp.app/Contents/Frameworks/DevMateKit.framework/Versions/A/Resources/Problem Reporter Sandboxed.app/Contents/MacOS/Problem Reporter Sandboxed" )] Refer to App Sandbox page at https://developer.apple.com/devcenter/mac/app-sandbox/ for more information on sandboxing your app.
```
I've just tried `DevMateKit_MAS 1.8.3` and it works well.

Xcode Version 10.0 (10A254a)
macOS Mojave 10.14

I am installing DevMateKit_MAS using cocoapods.

**Comment by dimaty** [comment]
Yes, `com.apple.security.app-sandbox` key was removed from entitlemets file, beacause it contains `com.apple.security.inherit = YES` value which means that at runtime app will inherit all security properties of it's parent process. Moving back `com.apple.security.app-sandbox` breaks this functionality (running problem reported after main app crash).  Need to talk with Apple engineers about this situation.

**Comment by teologov** [comment]
Got it, thanks for the detailed response @dimaty. Hopefully, there is a way to resolve this issue...

**Comment by dimaty** [comment]
Hi @teologov.
Check a new version of DevMateKit (v1.9.1). I've moved back `com.apple.security.app-sandbox` key as the lates version of Mojave DP works fine with it 🎉

**Comment by teologov** [comment]
Hi @dimaty, I do confirm it works now. Awesome job, thanks!
