### ISSUE TITLE
Notarization and DevMateKit signing

### ISSUE THREAD

**Issue by rurza** [DevMate/DevMateKit#49]
Hey,
I've found that the only way to run the app with DevMateKit and hardened runtime enabled is to select "Disable Library Validation" in Runtime exceptions. That's because the DevMateKit is signed by you, unlike the rest of app. Is it okay?

`DevMateKit (1.9.2)`

**Comment by dimaty** [comment]
Not sure. But feel free to re-sign DevMateKit with own certificate.

**Comment by rurza** [comment]
Don't know how to make it. DevMateKit isn't visible as a target in Xcode project settings for some reason :/

<img width="1007" alt="screenshot 2018-12-28 at 12 45 00" src="https://user-images.githubusercontent.com/2467137/50514420-65c48800-0a9e-11e9-8be4-27de4b459d19.png">

**Comment by rurza** [comment]
Thanks :)

**Comment by jroa919** [comment]
@rurza Not sure if you're still having this issue (I ran into this recently), but for the benefit of others whom may encounter this in the future, this is what I did to resolve this error:

`dyld: Library not loaded: @rpath/DevMateKit.framework/Versions/A/DevMateKit`
Try adding `--deep` to `Other Code Signing Flags` in `Build Settings`

**Comment by rurza** [comment]
Forgot to close the issue 🤦‍♂️
