### ISSUE TITLE
Project with DevMate is crashing on the launch

### ISSUE THREAD

**Issue by serejahh** [DevMate/DevMateKit#60]
Hi. It seems you use `libcrypto` without version, so the project is crashing with Xcode 11. Could you fix it ASAP? We need to release a beta version for macOS Catalina using the latest Xcode

Crash report:
```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/usr/lib/libcrypto.dylib
abort() called
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
```

**Comment by tonyarnold** [comment]
We're seeing this now in Reveal, too. This is a production issue now. Could someone please confirm that they're looking at this?

**Comment by tonyarnold** [comment]
I can see that Kevlar has been updated in the dashboard: https://docs.devmate.com/docs/kevlar-release-notes 

DevMate team: might be time to address/close issues here that you've addressed?

**Comment by avalore** [comment]
@tonyarnold Yep, thanks!
Kevlar `4.3.1` fixes this issue.

**Comment by paganel** [comment]
How to get the latest version Kevlar?

In DevMate Dashboard only  Available Version
4.3   /   Apr 12, 2018

**Comment by avalore** [comment]
@paganel investigating. What's your seller ID?

**Comment by paganel** [comment]
#152
gerasim.sergey (at) gmail.com

#2705
gerasim.sergey+1 (at) gmail.com

**Comment by paganel** [comment]
any update?

**Comment by avalore** [comment]
@paganel Do you have the updated version in your dashboard now?

**Comment by paganel** [comment]
Да, спасибо большое, теперь уже новая версия доступна

**Comment by muyexi** [comment]
@avalore Hi, my Kevlar version is still 4.3, my id is muyexi (at) gmail.com.
