### ISSUE TITLE
Apple Silicon support needed

### ISSUE THREAD

**Issue by guidedways** [DevMate/DevMateKit#64]
We still need to use DevMateKit's framework for old licenses and need support for Apple Silicon please.

**Comment by dimaty** [comment]
Working on it.

**Comment by dimaty** [comment]
@guidedways I've just released DevMateKit v1.10 that is universal binary. Next our step is to do the same for `libKevlar`.

**Comment by guidedways** [comment]
@dimaty thank you! Much appreciated!

**Comment by macmade** [comment]
Thanks @dimaty - When can we expect an updated version of libkevlar?

**Comment by dimaty** [comment]
@macmade @guidedways Our team is working on it, but for now it's hard to say about estimation. But if you need libKevlar for yesterday, please mail me directly to dimaty@macpaw.com and I'll build it for your app using local machine.

**Comment by dimaty** [comment]
Infrastructure for building Kevlar library was updated and now you can download new version of this lib from dashboard settings page.
