### ISSUE TITLE
Enhancement: define module

### ISSUE THREAD

**Issue by macmade** [DevMate/DevMateKit#7]
It would be great if the `DevMateKit` framework could define a **module**, so we could use `@import` statements, instead of `#import`.

**Comment by tonyarnold** [comment]
This forces the use of an Objective-C bridging header in Swift projects, too.

**Comment by dimaty** [comment]
At this time DevMateKit does not support module feature because it has macro inside master header
```
// If you are using your own copy of Sparkle.framework just define
// USED_CUSTOM_SPARKLE_FRAMEWORK macro.
#ifndef USED_CUSTOM_SPARKLE_FRAMEWORK
#import "DevMateSparkle.h"
#endif
```
So if you're using framework in Swift target you need to import `<DevMateKit/DevMateKit.h>` in bridging header.
If you're using your own copy of Sparkle for updates add to bridging header next:
```
#define USED_CUSTOM_SPARKLE_FRAMEWORK
#import <DevMateKit/DevMateKit.h>
```
